### ISSUE TITLE
 http://prlab.tudelft.nl/david-tax/dd_tools.html DD Toolbox outdated

### ISSUE THREAD

**Issue by ZHUANGHP** [Chandan-IITI/One-Class-Kernel-ELM#1]
Hi, the link for the DD Toolbox seems to be outdated. Could you point me a new link? Thanks!

**Comment by Chandan-IITI** [comment]
Updated the link... You can find it on :

[DD Toolbox](https://www.tudelft.nl/ewi/over-de-faculteit/afdelingen/intelligent-systems/pattern-recognition-bioinformatics/pattern-recognition-bioinformatics/data-and-software/dd-tools
)

**Comment by ZHUANGHP** [comment]
@Chandan-IITI Thanks!
